FROM node:10
WORKDIR /code
RUN git clone https://github.com/math-learning/users-service.git
WORKDIR ./users-service 
RUN git pull
RUN npm install
EXPOSE 7000
ENV DOCKER true
CMD ["npm", "run", "start:watch"]
