FROM node:10
WORKDIR /code
RUN git clone https://github.com/math-learning/exercises-service.git
RUN mv -v ./exercises-service/* .
RUN npm install
EXPOSE 9000
ENV DOCKER=true
CMD ["npm", "run", "start:watch"]