FROM node:10

ENV PATH /usr/src/app/node_modules/.bin:$PATH

WORKDIR /usr/src/app
RUN git clone https://github.com/math-learning/math-learning-frontend.git
RUN mv -v ./math-learning-frontend/* .
RUN npm install --only=dev
RUN npm install --silent

EXPOSE 3000

CMD [ "npm", "start"]