FROM node:10
WORKDIR /code
ARG CACHE_DATE=2016-01-01
RUN git clone https://github.com/math-learning/users-service.git
WORKDIR ./users-service 
ARG CACHE_DATE=2016-01-01
RUN git pull
RUN npm install
EXPOSE 7000
ENV DOCKER true
CMD ["npm", "run", "start:watch"]
